"""Tune a Random Forest model and log the experiment manually with MLflow.

The baseline script uses MLflow autolog. This file keeps the tuned experiment
separate so parameters, metrics, model files, and evaluation artifacts are
logged explicitly and can also be sent to DagsHub when needed.
"""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
from typing import Any

import joblib
import mlflow
import mlflow.sklearn
import numpy as np
import pandas as pd
from mlflow.models import infer_signature
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    f1_score,
    log_loss,
    precision_score,
    recall_score,
    roc_auc_score,
)
from sklearn.model_selection import RandomizedSearchCV


LABELS = [0, 1]
LABEL_NAMES = ["not_canceled", "canceled"]


def configure_tracking(tracking_uri: str, experiment_name: str, use_dagshub: bool) -> None:
    """Configure MLflow tracking locally or through DagsHub."""
    if use_dagshub:
        try:
            import dagshub
        except ImportError as exc:
            raise ImportError("Install dagshub or run without --use-dagshub.") from exc

        repo_owner = os.getenv("DAGSHUB_REPO_OWNER", "adha20")
        repo_name = os.getenv("DAGSHUB_REPO_NAME", "SMSML_Muhammad_Adha")
        dagshub.init(repo_owner=repo_owner, repo_name=repo_name, mlflow=True)
    else:
        mlflow.set_tracking_uri(tracking_uri)
    mlflow.set_experiment(experiment_name)


def load_json(path: Path, default: Any) -> Any:
    """Read a JSON metadata file, falling back to a safe default."""
    if not path.exists():
        return default
    return json.loads(path.read_text(encoding="utf-8"))


def load_dataset(data_dir: Path, target_column: str) -> tuple[pd.DataFrame, pd.Series, pd.DataFrame, pd.Series, dict, dict, list[str]]:
    """Load train/test splits and metadata generated by preprocessing."""
    train_path = data_dir / "train.csv"
    test_path = data_dir / "test.csv"
    if not train_path.exists() or not test_path.exists():
        raise FileNotFoundError(f"Preprocessed train/test files were not found in {data_dir}")

    train_data = pd.read_csv(train_path)
    test_data = pd.read_csv(test_path)
    x_train = train_data.drop(columns=[target_column])
    y_train = train_data[target_column]
    x_test = test_data.drop(columns=[target_column])
    y_test = test_data[target_column]

    label_mapping = load_json(data_dir / "label_mapping.json", {"0": "not_canceled", "1": "canceled"})
    dataset_info = load_json(data_dir / "dataset_info.json", {})
    feature_columns = load_json(data_dir / "feature_columns.json", list(x_train.columns))
    return x_train, y_train, x_test, y_test, label_mapping, dataset_info, feature_columns


def build_search(random_state: int, cv: int, n_iter: int, n_jobs: int) -> RandomizedSearchCV:
    """Create the RandomizedSearchCV object for model tuning."""
    estimator = RandomForestClassifier(
        bootstrap=True,
        class_weight="balanced_subsample",
        n_jobs=n_jobs,
        random_state=random_state,
    )
    param_distributions = {
        "n_estimators": [80, 120, 180],
        "max_depth": [12, 18, None],
        "min_samples_split": [2, 5, 10],
        "min_samples_leaf": [1, 2, 4],
        "max_features": ["sqrt", "log2", 0.6],
    }
    return RandomizedSearchCV(
        estimator=estimator,
        param_distributions=param_distributions,
        n_iter=n_iter,
        scoring="f1",
        cv=cv,
        random_state=random_state,
        n_jobs=n_jobs,
        verbose=1,
        refit=True,
        return_train_score=True,
    )


def make_feature_importance(model: RandomForestClassifier, feature_names: list[str], limit: int = 50) -> pd.DataFrame:
    """Convert the most important model features into a tabular artifact."""
    importances = model.feature_importances_
    order = np.argsort(importances)[::-1][:limit]
    return pd.DataFrame(
        {
            "rank": np.arange(1, len(order) + 1),
            "feature": [feature_names[index] for index in order],
            "importance": [float(importances[index]) for index in order],
        }
    )


def write_json(path: Path, value: Any) -> None:
    """Write structured artifacts in a readable JSON format."""
    path.write_text(json.dumps(value, indent=2), encoding="utf-8")


def parse_args() -> argparse.Namespace:
    """Parse command-line options for tuning and manual MLflow logging."""
    parser = argparse.ArgumentParser(description="Tune hotel booking cancellation model and log manually to MLflow.")
    parser.add_argument("--data-dir", type=Path, default=Path("hotel_bookings_preprocessing"))
    parser.add_argument("--target-column", default="is_canceled")
    parser.add_argument("--tracking-uri", default="file:./mlruns")
    parser.add_argument("--experiment-name", default="Hotel Booking Cancellation - Random Forest Tuning")
    parser.add_argument("--model-output", type=Path, default=Path("model_output_tuned"))
    parser.add_argument("--artifact-dir", type=Path, default=Path("training_artifacts"))
    parser.add_argument("--random-state", type=int, default=42)
    parser.add_argument("--cv", type=int, default=3)
    parser.add_argument("--n-iter", type=int, default=4)
    parser.add_argument("--n-jobs", type=int, default=-1)
    parser.add_argument("--use-dagshub", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    configure_tracking(args.tracking_uri, args.experiment_name, args.use_dagshub)
    x_train, y_train, x_test, y_test, label_mapping, dataset_info, feature_columns = load_dataset(
        args.data_dir,
        args.target_column,
    )

    search = build_search(args.random_state, args.cv, args.n_iter, args.n_jobs)
    with mlflow.start_run(run_name="manual_random_forest_tuning"):
        # Log the experiment context before training so each run is traceable.
        mlflow.log_param("model_type", "RandomForestClassifier")
        mlflow.log_param("dataset_dir", str(args.data_dir))
        mlflow.log_param("target_column", args.target_column)
        mlflow.log_param("cv", args.cv)
        mlflow.log_param("n_iter", args.n_iter)
        mlflow.log_param("random_state", args.random_state)
        mlflow.log_param("use_dagshub", args.use_dagshub)
        mlflow.log_param("train_rows", len(x_train))
        mlflow.log_param("test_rows", len(x_test))
        mlflow.log_param("feature_count", x_train.shape[1])

        # Fit the search object and evaluate the best model on the test split.
        search.fit(x_train, y_train)
        best_model: RandomForestClassifier = search.best_estimator_
        predictions = best_model.predict(x_test)
        probabilities = best_model.predict_proba(x_test)[:, 1]
        probability_matrix = best_model.predict_proba(x_test)

        metrics = {
            "accuracy": accuracy_score(y_test, predictions),
            "precision": precision_score(y_test, predictions, zero_division=0),
            "recall": recall_score(y_test, predictions, zero_division=0),
            "f1": f1_score(y_test, predictions, zero_division=0),
            "f1_macro": f1_score(y_test, predictions, average="macro", zero_division=0),
            "f1_weighted": f1_score(y_test, predictions, average="weighted", zero_division=0),
            "roc_auc": roc_auc_score(y_test, probabilities),
            "log_loss": log_loss(y_test, probability_matrix, labels=LABELS),
            "best_cv_f1": search.best_score_,
        }
        for metric_name, metric_value in metrics.items():
            mlflow.log_metric(metric_name, float(metric_value))

        for param_name, param_value in search.best_params_.items():
            mlflow.log_param(f"best_{param_name}", param_value)

        # Store evaluation outputs as files so they are easy to inspect later.
        args.artifact_dir.mkdir(parents=True, exist_ok=True)
        cv_results_path = args.artifact_dir / "cv_results.csv"
        report_path = args.artifact_dir / "classification_report.json"
        matrix_path = args.artifact_dir / "confusion_matrix.json"
        params_path = args.artifact_dir / "best_params.json"
        importance_path = args.artifact_dir / "feature_importance.csv"
        sample_path = args.artifact_dir / "sample_predictions.csv"

        pd.DataFrame(search.cv_results_).to_csv(cv_results_path, index=False)
        write_json(report_path, classification_report(y_test, predictions, target_names=LABEL_NAMES, output_dict=True, zero_division=0))
        write_json(matrix_path, {"labels": LABEL_NAMES, "matrix": confusion_matrix(y_test, predictions, labels=LABELS).tolist()})
        write_json(params_path, search.best_params_)
        make_feature_importance(best_model, list(x_train.columns)).to_csv(importance_path, index=False)
        pd.DataFrame(
            {
                "actual": y_test.head(200).to_numpy(),
                "prediction": predictions[:200],
                "cancellation_probability": probabilities[:200],
            }
        ).to_csv(sample_path, index=False)

        mlflow.log_dict(label_mapping, "label_mapping.json")
        mlflow.log_dict(dataset_info, "dataset_info.json")
        mlflow.log_dict({"feature_columns": feature_columns}, "feature_columns.json")
        mlflow.log_artifacts(str(args.artifact_dir), artifact_path="evaluation")

        # Include the model signature to make serving and validation clearer.
        signature = infer_signature(x_train.head(5), best_model.predict(x_train.head(5)))
        mlflow.sklearn.log_model(
            sk_model=best_model,
            artifact_path="model",
            signature=signature,
            input_example=x_train.head(3),
        )

        # Export a lightweight serving bundle outside MLflow for local API usage.
        args.model_output.mkdir(parents=True, exist_ok=True)
        joblib.dump(best_model, args.model_output / "model.joblib")
        write_json(args.model_output / "label_mapping.json", label_mapping)
        write_json(args.model_output / "feature_columns.json", feature_columns)
        write_json(args.model_output / "best_params.json", search.best_params_)
        mlflow.log_artifacts(str(args.model_output), artifact_path="serving_model")

        print("Best params:", search.best_params_)
        print(f"Accuracy: {metrics['accuracy']:.4f}")
        print(f"Precision: {metrics['precision']:.4f}")
        print(f"Recall: {metrics['recall']:.4f}")
        print(f"F1: {metrics['f1']:.4f}")
        print(f"ROC AUC: {metrics['roc_auc']:.4f}")
        print(f"Tuned model saved to: {args.model_output.resolve()}")


if __name__ == "__main__":
    main()

